### ISSUE TITLE
Try multiple effects

### ISSUE THREAD

**Issue by oliverjam** [fac-17/leonie-jan-app#19]
https://github.com/fac-17/leonie-jan-app/blob/c1722c2cfe425623a75435accf6b27f940880015/src/components/PlayingField.js#L22

This effect function is pretty long, and actually has two responsibilities: setting up a keydown event listener and starting the interval to increment the score.

Since you can have as many `useEffect` calls as you like it's nice to have one per "concern"

**Comment by samjam48** [comment]
@reubengt this might be useful for you!
