### ISSUE TITLE
Using index as key

### ISSUE THREAD

**Issue by ZooeyMiller** [fac-17/leonie-jan-app#26]
https://github.com/fac-17/leonie-jan-app/blob/c1722c2cfe425623a75435accf6b27f940880015/src/components/HighScoreBoard.js#L18

Though I don't think it will actually manifest in a bug here - it is best not to use indexes as keys in react. If you get into the habit of doing it, you may end up doing it in a situation where it does cause a bug. 

see: https://medium.com/@robinpokorny/index-as-a-key-is-an-anti-pattern-e0349aece318

**Comment by crianonim** [comment]
good point! The reason for that was, this is at the moment very static component and we had no time;)
